[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ClinicallyOrientedPsychology"
authors = [{name = "Justpsychiatry", email = "Justpsychiatry@outlook.com"}]
dynamic = ["version", "description"]
